
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 17 06:20:01 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 47;
  public static final int CHAR = 50;
  public static final int CONST = 7;
  public static final int AND_AND = 30;
  public static final int MINUS_MINUS = 33;
  public static final int LPAREN = 43;
  public static final int SEMI = 40;
  public static final int CONTINUE = 13;
  public static final int INT = 49;
  public static final int MINUS = 35;
  public static final int IS_GRE = 26;
  public static final int IS_LESS = 28;
  public static final int CHARACTER = 55;
  public static final int RPAREN = 44;
  public static final int RECORD = 21;
  public static final int BOOL = 51;
  public static final int COMMA = 42;
  public static final int IS_GEQ = 27;
  public static final int CLASS = 17;
  public static final int DIV = 37;
  public static final int OR_OR = 31;
  public static final int PLUS = 34;
  public static final int IF = 8;
  public static final int THIS = 22;
  public static final int DOT = 20;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int PLUS_PLUS = 32;
  public static final int RBRACKET = 48;
  public static final int EQUAL = 39;
  public static final int TRUE = 15;
  public static final int SUPER = 23;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int PERCENT = 38;
  public static final int IS_NEQ = 25;
  public static final int NULL = 52;
  public static final int NUMBER = 53;
  public static final int IDENT = 54;
  public static final int BREAK = 12;
  public static final int VOID = 6;
  public static final int TIMES = 36;
  public static final int COLON = 41;
  public static final int LBRACE = 45;
  public static final int ELSE = 9;
  public static final int IS_EQ = 24;
  public static final int READ = 3;
  public static final int GOTO = 14;
  public static final int WHILE = 11;
  public static final int IS_LEQ = 29;
  public static final int RBRACE = 46;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int FALSE = 16;
  public static final int PRINT = 4;
  public static final int DO = 10;
}

